<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_ctl00ctl00mainContentmainCont_755761</name>
   <tag></tag>
   <elementGuidId>ec1bbbd9-4b50-47b1-98f6-8d3b659295de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_txtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>675cc60e-8f4f-4661-b61f-4047cc5a5a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$txtPassword</value>
      <webElementGuid>7e47d787-08f7-427b-adb6-3edeeb69ae23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>25c25477-ab06-4558-bcb4-7831eb4f4ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_txtPassword</value>
      <webElementGuid>35a8f512-b98a-461e-bb04-8ccbfaa429fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4a06a3c0-fa40-46fb-b6d2-3a69b33b4488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>ac435996-2a28-41e7-8841-2f2ffcf3d076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_txtPassword&quot;)</value>
      <webElementGuid>6adb3726-2e69-4d25-ae5d-bdfc9a8dc03b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_txtPassword']</value>
      <webElementGuid>e100464d-61c4-4865-9531-347b00f62dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_pnlMemeberLogIn']/div/div/div[2]/input</value>
      <webElementGuid>dc15df53-43b7-4ef2-8304-31b250da541e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>f57f23ee-5797-46bd-8d6d-b27708e150d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$txtPassword' and @type = 'password' and @id = 'mainContent_mainContent_txtPassword' and @placeholder = 'Password']</value>
      <webElementGuid>b7f5ddc8-e2c2-4b9a-82c5-e7bfb6d533e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
