<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember this device for 30 days_ctl0_098541</name>
   <tag></tag>
   <elementGuidId>75c4a848-3781-4314-8a4c-83b988bad94a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mainContent_mainContent_CodeTextBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainContent_mainContent_CodeTextBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08ae0729-eef6-4ad9-94d8-bf650bd87266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$mainContent$mainContent$CodeTextBox</value>
      <webElementGuid>8e348309-c7af-4b7a-a2bd-c5e8f3dcba9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03a83b8b-560d-4091-baf0-1001e04db85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>db7de43f-7927-4864-844a-61c996146d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainContent_mainContent_CodeTextBox</value>
      <webElementGuid>abb36801-e16f-4c6c-8437-e31b5f82356f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de8173f6-e14c-47a0-ae28-d36a96c2116e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter security code</value>
      <webElementGuid>98f2f107-8502-4432-8121-322073428652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_CodeTextBox&quot;)</value>
      <webElementGuid>45f05521-c4eb-450f-b470-dcc3360ca834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mainContent_mainContent_CodeTextBox']</value>
      <webElementGuid>43d57831-7fa3-4ab9-9024-3b7666eda519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent_mainContent_CodeEntryPanel']/input</value>
      <webElementGuid>2809d412-e3b3-404a-8947-b44674c8e29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5ae8fc81-4ef9-42d3-8d5d-121667a7b4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$mainContent$mainContent$CodeTextBox' and @type = 'text' and @id = 'mainContent_mainContent_CodeTextBox' and @placeholder = 'Enter security code']</value>
      <webElementGuid>e2bc7028-e783-4392-b404-69c848eb39ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
