<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Owens Corning</name>
   <tag></tag>
   <elementGuidId>6d81546a-7981-4f66-91d4-b4ebdd1e26b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mainContent_mainContent_ucTenantSelection_rptTenants_lnkTenant_0']/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eac7e423-c6d7-47eb-a971-407e8fd88978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Owens Corning</value>
      <webElementGuid>601c3200-47f6-487d-bd26-106bc680690d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent_mainContent_ucTenantSelection_rptTenants_lnkTenant_0&quot;)/div[@class=&quot;media&quot;]/div[@class=&quot;tenant-name media-body&quot;]/span[1]</value>
      <webElementGuid>4776928d-9160-4ba9-8748-b05b30f57d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='mainContent_mainContent_ucTenantSelection_rptTenants_lnkTenant_0']/div/div[2]/span</value>
      <webElementGuid>f514288b-c291-429f-9c6c-8f4bd2ae615d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signed in as: v.b@mail.com'])[1]/following::span[1]</value>
      <webElementGuid>a17c8b1f-1602-4762-bd60-6a417c3d1fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NileshTest'])[1]/preceding::span[1]</value>
      <webElementGuid>c08365d6-63c5-48ba-92e6-149cc39937d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Login'])[1]/preceding::span[2]</value>
      <webElementGuid>5fed6345-7639-4649-b82b-3bb18704c5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Owens Corning']/parent::*</value>
      <webElementGuid>abd24a7b-940a-4a56-9874-0da153adc442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>cb1acc35-e942-4990-9f4c-cd4acf23e20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Owens Corning' or . = 'Owens Corning')]</value>
      <webElementGuid>be6ad9a9-b854-4b18-a60a-d609c4d0a0cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
